# Defaults tasks for role ipsilon
- name: Importing specific distro variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- ansible.builtin.include_role:
    name: mysql
  tags:
    - db

- name: Creating mandatory (local) DB 
  ansible.builtin.include_role: 
    name: mysql
    tasks_from: db
  vars:
    mysql_db_user: "{{ ipsilon_db_user }}"
    mysql_db_pass: "{{ ipsilon_db_pass }}"
    mysql_db_name: "{{ ipsilon_db_name }}"
  tags:
    - db

- name: Creating mandatory static (local) DB 
  ansible.builtin.include_role: 
    name: mysql
    tasks_from: db
  vars:
    mysql_db_user: "{{ ipsilon_db_user }}"
    mysql_db_pass: "{{ ipsilon_db_pass }}"
    mysql_db_name: "{{ ipsilon_db_name }}_static"
  tags:
    - db

- name: Needed .repo template for ipsilon pkgs
  ansible.builtin.template:
    src: centos-auth-ipsilon.repo.j2
    dest: /etc/yum.repos.d/centos-auth-ipsilon.repo
  tags:
    - repo

- ansible.builtin.include_tasks: ipa.yml
  when: ipsilon_ipa_auth
  tags:
    - ipa
    - init

- ansible.builtin.include_tasks: fas.yml
  when: ipsilon_fas_auth
  
- name: Ipsilon admins template
  ansible.builtin.template:
    src: ipsilon-admins.sql.j2
    dest: /etc/ipsilon/idp/ipsilon-admins.sql
  register: ipsilon_admins 
  tags:
    - init
    - admins

- name: Configuring ipsilon admins
  mysql_db:
    name: "{{ ipsilon_db_name }}"
    state: import
    target: /etc/ipsilon/idp/ipsilon-admins.sql
  when: ipsilon_admins is changed
  tags:
    - init
    - admins

- name: Configuring httpd
  ansible.builtin.import_role:
    name: httpd
  vars:
    httpd_tls: "{{ ipsilon_httpd_tls }}"

- name: Configuring httpd vhost
  ansible.builtin.template:
    src: 02_ipsilon_vhost.conf.j2
    dest: /etc/httpd/conf.d/02_ipsilon_vhost.conf
    mode: 0644
  notify:
    - restart_httpd
  tags:
    - httpd

- name: Configuring https
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  notify:
    - restart_httpd
  with_items:
    - ssl-ipsilon-vhost.conf
  when: ipsilon_httpd_tls  
  tags:
    - httpd

- ansible.builtin.import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ ipsilon_httpd_hostname }}"
  notify:
    - restart_httpd
  tags:
    - tls
  when: ipsilon_httpd_tls

- name: Branding ipsilon with logo
  copy:
    src: centos_logo.png
    dest: "{{ item }}"
    mode: 0644
  with_items:
    - /usr/share/ipsilon/ui/img/brand-lg.png
    - /usr/share/ipsilon/ui/img/brand.png
  tags:
    - theme

- name: Distributing openidc genkey script
  copy:
    src: genkey.py
    dest: /var/lib/ipsilon/idp/genkey.py
    mode: 0755

- name: Cleaning-up old sessions files
  cron:
    name: ipsilon session clean-up
    job: "find /var/lib/ipsilon/idp/sessions/ -mmin +1440 -delete"
    hour: '*'
    minute: '5'
  tags:
    - cron

- name: DB maintenance tasks 
  ansible.builtin.template:
    src: ipsilon-db-cleanup.j2 
    dest: /etc/cron.hourly/ipsilon-db-cleanup
    mode: '0755'
  tags:
    - db-tasks

- name: Ensuring backup user and jobs
  ansible.builtin.include_role:
    name: centos-backup
    tasks_from: client
  vars:
    - centos_role: ipsilon
    - role_backup_folders:
        - /var/lib/ipsilon 
  tags:
    - backup
